CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA2;
USE BD_APLICATIVO_MUSICA2;

CREATE TABLE IF NOT EXISTS ARTISTAS(
	CPF VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    QTD_MUSICA VARCHAR(100) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CUSTO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_EVENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS LANCA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ARTISTAS_CPF VARCHAR(20) ,
    FK_ALBUM_ID INTEGER,
    FOREIGN KEY ( FK_ARTISTAS_CPF) REFERENCES ARTISTAS(CPF),
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMTEM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ALBUM_ID INTEGER,
    FK_FAIXA_ID INTEGER,
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID)ON DELETE CASCADE,
    FOREIGN KEY (  FK_FAIXA_ID) REFERENCES FAIXA(ID)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERTENCE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_GENERO_ID INTEGER,
    FK_FAIXA_ID INTEGER,
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID) ON DELETE CASCADE,
    FOREIGN KEY ( FK_FAIXA_ID) REFERENCES FAIXA(ID)ON DELETE CASCADE
);





