CREATE DATABASE IF NOT EXISTS BD_CONSULTAS_MEDICAS;
USE BD_CONSULTAS_MEDICAS;

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(15) PRIMARY KEY,
    IDADE VARCHAR(100) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    HORARIO VARCHAR(24) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	CNPJ VARCHAR(20) PRIMARY KEY,
    HORARIO VARCHAR(24) NOT NULL,
    MOTIVO VARCHAR(255) NOT NULL,
    FK_PACIENTE_CPF VARCHAR(15),
    FK_MEDICO_CRM VARCHAR(20),
    FOREIGN KEY (FK_PACIENTE_CPF) REFERENCES PACIENTE(CPF)ON DELETE CASCADE,
    FOREIGN KEY (FK_MEDICO_CRM) REFERENCES MEDICO(CRM)ON DELETE CASCADE
);