CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT ,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO  VARCHAR(500) ,
    USU_PROFISSAO VARCHAR(200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIÚVO")NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MÉDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR (255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);

INSERT INTO USUARIO (USU_DATA_CADASTRO,USU_LOGIN,USU_DATANASC, USU_NOME,USU_SENHA,USU_EMAIL,USU_ESCOLARIDADE,USU_ESTADO_CIVIL, USU_ESTADO)
VALUES ("2025-12-09","BRUNO","2008-01-28","Bruno","123456789","brunodonizett@gmail.com","FUNDAMENTAL","SOLTEIRO","SP");

INSERT INTO USUARIO (USU_DATA_CADASTRO,USU_LOGIN,USU_DATANASC, USU_NOME,USU_SENHA,USU_EMAIL,USU_ESCOLARIDADE,USU_ESTADO_CIVIL, USU_ESTADO)
VALUES ("2025-12-09","FELIPE","2008-01-28","Felipe","123456789","felipedonizett@gmail.com","SUPERIOR","CASADO","SP");

INSERT INTO USUARIO (USU_DATA_CADASTRO,USU_LOGIN,USU_DATANASC, USU_NOME,USU_SENHA,USU_EMAIL,USU_ESCOLARIDADE,USU_ESTADO_CIVIL, USU_ESTADO)
VALUES ("2025-12-09","DIEGO","2008-01-28","Diego","123456789","diegodonizett@gmail.com","Médio","CASADO","SP");

SELECT *FROM USUARIO;

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    ENQ_DATA_INICAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(255) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL ,
    PRIMARY KEY (ENQ_CODIGO),
	FOREIGN KEY ( FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE
);

 INSERT INTO ENQUETE(ENQ_CODIGO, ENQ_DATA_FINAL, ENQ_DATA_INICAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO )
VALUES("20-09-2025","Sinuca dos crias","Bruno","1");

 INSERT INTO ENQUETE(ENQ_CODIGO,ENQ_DATA_FINAL,ENQ_DATA_INICAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO )
VALUES("20-09-2026","Sinuca dos crias","Felipe","1");

 INSERT INTO ENQUETE(ENQ_CODIGO,ENQ_DATA_FINAL,ENQ_DATA_INICAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO )
VALUES("20-09-2027","Sinuca dos crias","Diego","1");
    
SELECT * FROM ENQUETE;

CREATE TABLE  IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (URE_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
	FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

INSERT INTO USUARIO_RESPONDE_ENQUETE(URE_DATA,FK_USU_CODIGO ,FK_ENQ_CODIGO)
VALUES("20-12-2025","1","1");

INSERT INTO USUARIO_RESPONDE_ENQUETE(URE_CODIGO,URE_DATA,FK_USU_CODIGO ,FK_ENQ_CODIGO ,URE_CODIGO,FK_USU_CODIGO ,FK_ENQ_CODIGO)
VALUES("20-12-2025","1","1");

INSERT INTO USUARIO_RESPONDE_ENQUETE(URE_CODIGO,URE_DATA,FK_USU_CODIGO ,FK_ENQ_CODIGO ,URE_CODIGO,FK_USU_CODIGO ,FK_ENQ_CODIGO)
VALUES("20-12-2025","1","1");

SELECT *FROM USUARIO_RESPONDE_ENQUETE;

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PRE_DESCIRCAO VARCHAR(255) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
 RES_CODIGO INTEGER AUTO_INCREMENT,
 RES_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
 RES_CERTA VARCHAR(1) NOT NULL,
 FK_PER_CODIGO INTEGER NOT NULL,
 PRIMARY KEY (RES_CODIGO),
 FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS (PER_CODIGO) ON DELETE CASCADE
);




