CREATE DATABASE IF NOT EXISTS BD_GEREN_BIBLIO_DIG;
USE BD_GEREN_BIBLIO_DIG;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE VARCHAR(14) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE VARCHAR(14) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUMERO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FK_AUTOR_CPF VARCHAR(15),
    FOREIGN KEY (FK_AUTOR_CPF) REFERENCES AUTOR(CPF)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL_LIVRO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_LIVRO_DIGITAL_ID INTEGER ,
    FK_LEITOR_CPF VARCHAR(20),
    FOREIGN KEY ( FK_LEITOR_CPF) REFERENCES LEITOR(CPF),
    FOREIGN KEY (FK_LIVRO_DIGITAL_ID) REFERENCES LIVRO_DIGITAL(ID)ON DELETE CASCADE
);