CREATE DATABASE IF NOT EXISTS BD_GERENCIAR_PROJETOS;
USE BD_GERENCIAR_PROJETOS;

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(20) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJETOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ENTREGA VARCHAR(15) NOT NULL,
    PRAZO VARCHAR(15) NOT NULL,
    FK_PROJETOS_ID INTEGER,
    FOREIGN KEY (FK_PROJETOS_ID) REFERENCES PROJETOS(ID)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO_TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_TAREFA_ID INTEGER ,
    FK_FUNCIONARIO_CPF VARCHAR(20),
    FOREIGN KEY ( FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO(CPF),
    FOREIGN KEY (FK_TAREFA_ID) REFERENCES TAREFA(ID)ON DELETE CASCADE
);
