CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE;
USE BD_GESTAO_ESTOQUE;

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    QTD_PRODUTO VARCHAR(500) NOT NULL,
    VALOR DOUBLE NOT NULL,
	FK_CATEGORIA_ID INTEGER,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_PRODUTO_ID INTEGER ,
    FK_FORNECEDOR_CNPJ VARCHAR(20),
    FOREIGN KEY ( FK_FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ),
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(ID)ON DELETE CASCADE
);

