CREATE DATABASE IF NOT EXISTS BD_RES_HOTEL;
USE BD_RES_HOTEL;

CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ VARCHAR(20) PRIMARY KEY,
    LUGAR VARCHAR(255) NOT NULL,
    TAMANHO VARCHAR(14) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUMERO VARCHAR(255) NOT NULL,
	DESCRICAO VARCHAR(14) NOT NULL,
    FK_HOTEL_CNPJ VARCHAR(20),
    FOREIGN KEY (FK_HOTEL_CNPJ) REFERENCES HOTEL(CNPJ)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO_HOSPEDE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_QUARTO_ID INTEGER ,
    FK_HOSPEDE_CPF VARCHAR(20),
    FOREIGN KEY ( FK_HOSPEDE_CPF) REFERENCES HOSPEDE(CPF),
    FOREIGN KEY (FK_QUARTO_ID) REFERENCES QUARTO(ID)ON DELETE CASCADE
);