CREATE DATABASE IF NOT EXISTS BD_RESERVAS_AEREAS;
USE BD_RESERVAS_AEREAS;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(20) PRIMARY KEY,
    TELEFONE VARCHAR(15) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOO(
	CNPJ VARCHAR(20) PRIMARY KEY,
    DESTINO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CLASSIE VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FK_PASSAGEIRO_CPF VARCHAR(20) NOT NULL,
     FK_VOO_CNPJ VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_PASSAGEIRO_CPF) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_VOO_CNPJ) REFERENCES VOO(CNPJ)ON DELETE CASCADE
    
);