CREATE DATABASE IF NOT EXISTS BD_STREAM_VIDEO;
USE BD_STREAM_VIDEO;


CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    IDADE VARCHAR(100) NOT NULL,
    DESCRIÇÃO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE,
	FK_CATEGORIA_ID INTEGER,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VISUALIZAÇÃO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    INTERACOES VARCHAR(500) NOT NULL,
    CURTIDAS VARCHAR(255) NOT NULL,
	FK_VIDEO_ID INTEGER,
    FOREIGN KEY (FK_VIDEO_ID) REFERENCES VIDEO(ID)ON DELETE CASCADE
);